### ISSUE TITLE
🔧 THE WAY HOW TO FIX ❗

### ISSUE THREAD

**Issue by Obektev** [MateusAquino/ImageEmojis#4]
If you have problem that nothing happens, when you click RMB, do the following:
Open plugin's js file in any text-editor (like notepad)
Find 
`let chatInput = this.select('slateTextArea');` (45 string)
REPLACE 'slateTextArea' on 'textAreaSlate'

Save and reload plugin
That's all
--------------------------------------------------------
Если у вас есть проблема, что ничего не происходит, когда вы нажимаете ПКМ, сделайте следующее:
Откройте js-файл плагина любым текстовым редактором (можно блокнотом)
Найдите
`let chatInput = this.select('slateTextArea');` (строка 45)
ЗАМЕНИТЕ 'slateTextArea' на 'textAreaSlate'

Сохраните и перезагрузите плагин
Вот и все

**Comment by MateusAquino** [comment]
I haven't used this plugin since a long time because I was too lazy to update BetterDiscord every time, but thank you for the suggestion :)

I've updated the plugin.js file!
